spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

liquibase:
  change-log: classpath:db.changelog/db.changelog-master.xml

