server:
  port: 8443
  ssl:
    key-alias: domain
    key-store-type: PKCS12
    key-store: classpath:keys.p12
    key-store-password: password

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/database
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  require-ssl: true

liquibase:
  change-log: classpath:db.changelog/db.changelog-master.xml
