server:
  context-path: /app
  port: 8443
  ssl:
    key-alias: domain
    key-store-type: JKS
    key-store: classpath:keys.jks
    key-store-password: password

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/database
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  require-ssl: true
